### ISSUE TITLE
Theos repo

### ISSUE THREAD

**Issue by codwam** [theos/orion#13]
Why should the system version be greater than 12.2 and will not support lower versions?

**Comment by kabiroberai** [comment]
Swift didn't have [ABI stability](https://www.swift.org/blog/abi-stability-and-more/) until iOS 12.2, which means that there are various issues using Swift tweaks on versions older than that, which may be brought about by conflicting versions of Swift between tweaks or between the host app and your tweak. Consequently, there aren't any plans to support versions lower than 12.2: it would be difficult at best and nigh-impossible at worst.
