### ISSUE TITLE
Building on iOS?

### ISSUE THREAD

**Issue by zx500xl** [theos/orion#21]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install Orion on iOS device
2. Install swift-toolchain (for iOS) and libswift
3. create swift_tweak (using nic.pl)
4. run

What happens?
-------------
Build failed

What were you expecting to happen?
----------------------------------
Build the tweak

Any logs, error output, etc?
----------------------------

> Making all for tweak swifttweakorion…
==> Building Swift support tools…
error: unable to invoke subcommand: /usr/bin/swift-build (No such file or directory)
Failed to build swift-support: command failed: SPM_THEOS_BUILD=1 swift build -c release --package-path /opt/theos/vendor/swift-support --build-path /opt/theos/vendor/swift-support/.theos_build
make[2]: *** [/opt/theos/makefiles/instance/rules.mk:197: internal-swifttweakorion-swift-support] Error 2
make[1]: *** [/opt/theos/makefiles/instance/rules.mk:62: before-swifttweakorion-all] Error 2
make: *** [/opt/theos/makefiles/master/rules.mk:163: swifttweakorion.all.tweak.variables] Error 2

Any other comments?
-------------------
Is it even possible to build a tweak on iOS?

What versions of software are you using?
----------------------------------------
**Operating System:** …
iOS 14.0.1

**Toolchain Version:** …
swift-toolchain 4.0.3-1
libswift4 4.2.1-2

**SDK Version:** …

**Comment by L1ghtmann** [comment]
This issue has to do with the `swift` provided by your jailbreak. Closing as not Theos/Orion related.
