### ISSUE TITLE
How can I return orig with the code below???

### ISSUE THREAD

**Issue by recoveryawareness** [theos/orion#25]
class TAEDarkColorPaletteHook: ClassHook<TAEDarkColorPalette> {
    func backgroundColor() -> UIColor {
       return ThemeStorage.shared.config.getActiveTheme().backgroundColor.uiColor
    }
}

**Comment by L1ghtmann** [comment]
I'd recommend you consult the documentation available at https://orion.theos.dev/typealiases/classhook. I believe the code would be:

```swift
class TAEDarkColorPaletteHook: ClassHook {
func backgroundColor() -> UIColor {
return orig
}
}
```
