### ISSUE TITLE
Add/Fix support to be able to make rootless debs

### ISSUE THREAD

**Issue by chloekorzh** [theos/orion#26]
What are the steps to reproduce this issue?
-------------------------------------------
1. Compile package with rootless
What happens?
-------------
Doesn’t create a rootless deb, just a normal deb

What were you expecting to happen?
----------------------------------
I am expecting it to create a rootless deb

**Comment by kabiroberai** [comment]
This should be fixed by 1cd6905 — please update Theos and see if rootless debs build correctly now.
