### ISSUE TITLE
Plans to port to iOS 17?

### ISSUE THREAD

**Issue by ContinualDissapointment** [theos/orion#32]
What are the steps to reproduce this issue?
-------------------------------------------
1. Open Sileo
2. Add repo
3. Install

What happens?
-------------
Failure to install wrong iOS version

What were you expecting to happen?
----------------------------------
It fails to install

With Palera1n allowing iOS 17 to have JB it'd be awesome if this tweak were ported. A lot of things depend on it.

**Comment by TheGithubJoshua** [comment]
Does it physically not support iOS 17 or does it work if you update the depends firmware in the control file? @ContinualDissapointment

**Comment by ContinualDissapointment** [comment]
Sileo gives no error message, Zebra however states that firmware <<17.0
(Makes sense considering I'm on 17.0.3)
Will try modifying the depends line.

**Comment by ContinualDissapointment** [comment]
Modifying the fw line of the control file to be in-line with the current commit fixes the issue.
I do still think the pre-packaged debs should be updated as they are well behind the main-line master files and there are no instructions on how properly make a .deb from them. I had to rely on unpacking and modifying both it and the checksum before repacking.

**Comment by TheGithubJoshua** [comment]
K if the debs still aren’t updated I’d leave this open because it is still an issue.

**Comment by TheGithubJoshua** [comment]
Ah I see why the build containing the commit to change the control file failed, that’s why someone should fix it if it’s an issue with the code or just rerun the build

**Comment by TheGithubJoshua** [comment]
Someone should look into this: `/Users/runner/work/orion/orion/orion/Sources/Orion/ClassHook+Super.swift:5:29: no such module 'Orion_Private' `

**Comment by kabiroberai** [comment]
Technically speaking Orion should run just fine on iOS 17. I updated the control file in dd60a11d0fec56a52d5c6bf0850340e90748f16a but CI releases are currently failing due to an unrelated commit (556ca6f544bb3a5db195a4ce9c5a94446946a49b). I've been meaning to fix this but haven't had the time yet; will try to investigate over the coming week.

**Comment by TheGithubJoshua** [comment]
> Technically speaking Orion should run just fine on iOS 17. I updated the control file in [dd60a11](https://github.com/theos/orion/commit/dd60a11d0fec56a52d5c6bf0850340e90748f16a) but CI releases are currently failing due to an unrelated commit ([556ca6f](https://github.com/theos/orion/commit/556ca6f544bb3a5db195a4ce9c5a94446946a49b)). I've been meaning to fix this but haven't had the time yet; will try to investigate over the coming week.

that explains why reverting to it also fails.

**Comment by TheGithubJoshua** [comment]
Why do CI builds fail with a zip error after reverting to `9e2d22b`?

**Comment by L1ghtmann** [comment]
CI failing has been fixed and the v1.0.2 build has been published to Chariz.
