### ISSUE TITLE
Regarding the issue of hooking plist files

### ISSUE THREAD

**Issue by ghost** [theos/orion#38]
When I tried to annotate multiple bundles in the plist file, I found that it was not as stable as objective-c.

For example, in the plist file, I define it as follows:
```
{
	Filter = {
		Bundles = (
			"com.apple.springboard",
			"com.apple.mobilephone"
		);
	};
}
```
If 'com.apple.springboard' has the following classes and methods, it can hook:
```
class SBHook: ClassHook<SpringBoard> {
    func  applicationDidFinishLaunching:(_ arg: Any?) {
        orig.applicationDidFinishLaunching(arg);
   } 
}
```
But this class and method may not exist in ‘com.apple.mobilephone’, which will directly cause it to crash.
However, if OC is used, it will not crash due to inability to hit. If we want to solve this problem, are there any other solutions besides defining multiple target weaknesses?

**Comment by leptos-null** [comment]
The suggested approach for this would be to use a `HookGroup`, where hooks for one app are in one hook group, and the other app is in a separate hook group. You can utilize the `Tweak` `init` to activate the appropriate hook based on the bundle ID or other properties available at runtime. See the documentation for more information and examples: https://orion.theos.dev/protocols/hookgroup
