### ISSUE TITLE
Can't hook JSONObjectWithData

### ISSUE THREAD

**Issue by hugeBlack** [theos/orion#39]
What are the steps to reproduce this issue?
-------------------------------------------
1. Try to hook + [NSJSONSerialization  JSONObjectWithData:options:error:] with the following code:
```swift
class JSONDecodeHook: ClassHook<JSONSerialization> {
    class func JSONObjectWithData(_ data: NSData, options:JSONSerialization.ReadingOptions, error:NSError?) -> NSObject {
        NSLog("[MyTweak]hooked!")
        return orig.JSONObjectWithData(data, options:options, error:error)
    }
}
```

What happens?
-------------
I tried to hook this method to modify the outcome of some requests.

The app crashed with error:
```
EXC_BAD_ACCESSSIGSEGVKERN_INVALID_ADDRESS 
```

What were you expecting to happen?
----------------------------------
The method is successfully hooked

Any logs, error output, etc?
----------------------------
```
EXC_BAD_ACCESSSIGSEGVKERN_INVALID_ADDRESS 
```

Any other comments?
-------------------
I tried to hook this method with Frida and it was a success. I know that the target method is a class method, so I wonder if messed up with the method's signature?

P.S. I'm super new to objc so correct me if I'm wrong.

What versions of software are you using?
----------------------------------------
**Operating System:** 14.4.1

**Toolchain Version:** …

**SDK Version:** …

**Comment by Luki120** [comment]
Nowhere in the [docs](https://developer.apple.com/documentation/foundation/nsjsonserialization/1415493-jsonobjectwithdata?language=objc) it says it returns a `NSObject`, so start by fixing your signature, and I think you want `NSJSONSerialization` as the class name

**Comment by hugeBlack** [comment]
Thank you for your quick response! I did some research and found that `id` in objc is `Any?` in swift and `NSError * _Nullable *` should be `NSErrorPointer`. The hook is working now.

Here's the corrected version:
```swift
class JSONDecodeHook: ClassHook<JSONSerialization> {

    class func JSONObjectWithData(_ data: NSData, option opt:JSONSerialization.ReadingOptions, error:NSErrorPointer) -> Any? {
        NSLog("[MyTweak]hooked!")
        return orig.JSONObjectWithData(data, options:opt, error:error)
    }
}
```
